server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/healthmind
    username: healthmind
    password: healthmind123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 20000
      pool-name: UserServiceDevPool

  security:                    # ← spring ke andar, datasource ke bahar
    user:
      name: user
      password: disabled

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: devSecretKey404E635266556A586E3272357538782F413F442847284862
  access-token-expiry: 900000
  refresh-token-expiry: 604800000

logging:
  level:
    com.healthmind: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  health:
    redis:
      enabled: false          # ← yeh add karo
